#
# SwiftLint configuration file commonly used in STRV
#
# version 0.1
#


#
# Rule identifiers to exclude from running.
#
disabled_rules:
- statement_position

#
# Some rules are only opt-in. Find all the available rules by running: swiftlint rules
#
opt_in_rules:
- empty_count


#
# Paths to include during linting. `--path` is ignored if present.
#
included:
- ../Modules

#
# Paths to ignore during linting. Takes precedence over `included`.
#
excluded:
- Carthage
- Pods
- ../Modules/KollaborateUtilitiesModule/Example
- ../Modules/KollaborateLoginModule/Example
- ../Modules/KollaborateConsultationsModule/Example
- ../Modules/KollaborateChatModule/Example
- ../Modules/KollaborateVaultModule/Example


#
# Configure individual rules below.
#
vertical_whitespace:
    max_empty_lines: 2

force_cast: warning

identifier_name:
    max_length:
        warning: 60
    excluded:
        - id

empty_count: warning

trailing_whitespace:
    ignores_empty_lines: true

line_length:
    error: 300
    warning: 200

function_body_length:
    error: 150
    warning: 100

type_body_length:
    error: 900
    warning: 600

file_length:
    error: 1000
    warning: 700

#
# Place custom rules here.
#
custom_rules:
    comments_space: # From https://github.com/brandenr/swiftlintconfig
        name: "Space After Comment"
        regex: "(^ *//\\w+)"
        message: "There should be a space after //"
        severity: warning

    force_https: # From https://github.com/Twigz/Game
        name: "Force HTTPS over HTTP"
        regex: "((?i)http(?!s))"
        match_kinds: string
        message: "HTTPS should be favored over HTTP"
        severity: warning

    double_space: # From https://github.com/IBM-Swift/Package-Builder
        include: "*.swift"
        name: "Double space"
        regex: "([a-z,A-Z] \\s+)"
        message: "Double space between keywords"
        match_kinds: keyword
        severity: warning
